### ISSUE TITLE
Design conflict resolution API

### ISSUE THREAD

**Issue by syncush** [MapColonies/conflict-resolution#3]
One of our main goals is to expose a well-designed REST API for resolving a conflict,

A conflict can be resolved in 3 ways:

1. accept Local changes
2. accept Remote changes
3. Merge the two conflict into one resolution, meaning a user accepts some changes of the local, some changes of the remote, and merges them together into one resolved entity.

**Comment by galta95** [comment]
Some questions that i had  about this feature:
1. Relation conflicts. Relations have a members array, that just holds a reference to the original entities. how do we going to save a conflict that relate to a member of a way? remember: osm member element shows only the reference about the member and not actually the entity itself.  

2. Versions: I think we need to do a smarter version control and not to use the osm version control. we need to define a versions that include the server number and the entity number. somthing like this: 2.30 (server number 2, version number 30) but still we dont know what is the "best" entity. so once a while we need to create a conflicts to equal the version on every database.

3.If we have a  conflict about a node that relate to a way, we need to create a conflict to that way to? or we just going to create a conflict to the single node? (the version of the way need to cahnge?, what about a tags that relate to that way?)
